# Generated by Django 5.1.7 on 2025-06-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id_concepto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField()),
                ('es_fijo', models.BooleanField()),
                ('es_deb_cred', models.BooleanField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('permite_cuotas', models.BooleanField(null=True)),
                ('cant_cuotas', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'concepto',
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_liquidacion', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('mes_liquidacion', models.IntegerField()),
                ('anho_liquidacion', models.IntegerField()),
            ],
            options={
                'db_table': 'liquidacion',
            },
        ),
        migrations.CreateModel(
            name='ConceptoLiquidacion',
            fields=[
                ('id_concepto_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=5, max_digits=20)),
                ('id_concepto', models.ForeignKey(blank=True, db_column='id_concepto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='liquidacion.concepto')),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.empleado')),
            ],
            options={
                'db_table': 'concepto_liquidacion',
            },
        ),
        migrations.CreateModel(
            name='ConcEmpLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_concepto_liquidacion', models.ForeignKey(blank=True, db_column='id_concepto_liquidacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='liquidacion.conceptoliquidacion')),
                ('id_liquidacion', models.ForeignKey(blank=True, db_column='id_liquidacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='liquidacion.liquidacion')),
            ],
            options={
                'db_table': 'conc_emp_liquidacion',
            },
        ),
        migrations.CreateModel(
            name='DebCredMes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('anho', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=5, max_digits=15)),
                ('id_concepto', models.ForeignKey(db_column='id_concepto', on_delete=django.db.models.deletion.CASCADE, to='liquidacion.concepto')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
            options={
                'db_table': 'deb_cred_mes',
                'unique_together': {('id_empleado', 'id_concepto', 'mes', 'anho')},
            },
        ),
    ]
