# Generated by Django 5.1.7 on 2025-06-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
