# Generated by Django 5.1.7 on 2025-06-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0002_alter_concepto_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='cant_cuotas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='permite_cuotas',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
