# Generated by Django 5.1.7 on 2025-06-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0003_alter_concepto_cant_cuotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='id_liquidacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
