# Generated by Django 5.1.7 on 2025-03-30 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField()),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id_concepto', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField()),
                ('es_fijo', models.BooleanField()),
                ('es_deb_cred', models.BooleanField()),
                ('porcentaje', models.DecimalField(decimal_places=5, max_digits=5)),
                ('permite_cuotas', models.BooleanField()),
                ('cant_cuotas', models.IntegerField()),
            ],
            options={
                'db_table': 'concepto',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('departamento', models.CharField()),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id_liquidacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_liquidacion', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('mes_liquidacion', models.IntegerField()),
                ('anho_liquidacion', models.IntegerField()),
            ],
            options={
                'db_table': 'liquidacion',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tiene_beneficios', models.BooleanField()),
                ('salario_acordado', models.DecimalField(decimal_places=5, max_digits=15)),
                ('contrato_activo', models.BooleanField()),
                ('id_cargo', models.ForeignKey(blank=True, db_column='id_cargo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.cargo')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='DebCredMes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField()),
                ('anho', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=5, max_digits=15)),
                ('id_concepto', models.ForeignKey(blank=True, db_column='id_concepto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.concepto')),
            ],
            options={
                'db_table': 'deb_cred_mes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField()),
                ('apellidos', models.CharField()),
                ('cedula', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('email', models.CharField()),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField()),
                ('id_contrato', models.ForeignKey(blank=True, db_column='id_contrato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.contrato')),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.departamento')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='HistorialEmpleado',
            fields=[
                ('id_auditoria', models.IntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField()),
                ('campo_afectado', models.CharField()),
                ('valor_anterior', models.CharField()),
                ('valor_nuevo', models.CharField()),
                ('fecha_accion', models.DateField()),
                ('usuario_que_realizo', models.CharField()),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.empleado')),
            ],
            options={
                'db_table': 'historial_empleado',
            },
        ),
        migrations.CreateModel(
            name='ConceptoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_concepto', models.DecimalField(decimal_places=5, max_digits=20)),
                ('id_concepto', models.ForeignKey(blank=True, db_column='id_concepto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.concepto')),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.empleado')),
                ('id_liquidacion', models.ForeignKey(blank=True, db_column='id_liquidacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.liquidacion')),
            ],
            options={
                'db_table': 'concepto_liquidacion',
            },
        ),
        migrations.CreateModel(
            name='SaldoDescuento',
            fields=[
                ('id_saldo_descuento', models.IntegerField(primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=5, max_digits=15)),
                ('monto_pendiente', models.DecimalField(decimal_places=5, max_digits=15)),
                ('monto_cuota', models.DecimalField(decimal_places=5, max_digits=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField()),
                ('id_concepto', models.ForeignKey(blank=True, db_column='id_concepto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.concepto')),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.empleado')),
            ],
            options={
                'db_table': 'saldo_descuento',
            },
        ),
    ]
