# Generated by Django 5.1.7 on 2025-03-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='id_cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id_contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_cargo',
            field=models.ForeignKey(blank=True, db_column='id_cargo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.cargo'),
        ),
    ]
