# Generated by Django 5.1.7 on 2025-05-01 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField()),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('departamento', models.CharField()),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField()),
                ('apellidos', models.CharField()),
                ('cedula', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('email', models.CharField()),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField()),
                ('hijos_menores_18', models.IntegerField(default=0)),
                ('aplica_ips', models.BooleanField(default=True)),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.departamento')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='HistorialEmpleado',
            fields=[
                ('id_auditoria', models.IntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField()),
                ('campo_afectado', models.CharField()),
                ('valor_anterior', models.CharField()),
                ('valor_nuevo', models.CharField()),
                ('fecha_accion', models.DateField()),
                ('usuario_que_realizo', models.CharField()),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.empleado')),
            ],
            options={
                'db_table': 'historial_empleado',
            },
        ),
    ]
