# Generated by Django 5.1.7 on 2025-04-26 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField()),
                ('apellidos', models.CharField()),
                ('cedula', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('email', models.CharField()),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField()),
                ('id_cargo', models.ForeignKey(blank=True, db_column='id_cargo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.cargo')),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.departamento')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
