# Generated by Django 5.1.7 on 2025-06-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id_departamento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
