# Generated by Django 5.1.7 on 2025-05-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id_cargo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='aplica_ips',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hijos_menores_18',
            field=models.IntegerField(default=0),
        ),
    ]
