# Generated by Django 5.1.7 on 2025-06-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_acordado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contrato_activo', models.BooleanField(default=True)),
                ('tiene_beneficios', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empleado.empleado')),
            ],
            options={
                'db_table': 'contrato',
                'ordering': ['-contrato_activo', 'fecha_inicio'],
            },
        ),
    ]
