# Generated by Django 5.1.7 on 2025-04-27 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tiene_beneficios', models.BooleanField()),
                ('salario_acordado', models.DecimalField(decimal_places=5, max_digits=15)),
                ('contrato_activo', models.BooleanField()),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.empleado')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
    ]
