# Generated by Django 5.1.7 on 2025-05-09 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empleado.empleado'),
        ),
    ]
