# Generated by Django 5.1.7 on 2025-05-01 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_alter_contrato_id_empleado'),
        ('empleado', '0002_remove_empleado_id_cargo_empleado_aplica_ips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empleado.empleado'),
        ),
    ]
